name: Create Release and Build Binaries

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to create a release for debug"
        required: true
        default: "v0.0.0-test"

jobs:
  build:
    name: Build for ${{ matrix.os }}/${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["linux", "windows", "darwin"]
        arch: ["amd64", "arm64"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine Tag
        id: get_tag
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          fi

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Build and Package
        id: build-and-package
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          PROJECT_NAME: ${{ github.event.repository.name }}
          TAG: ${{ env.TAG }}
        run: |
          PACKAGE_DIR="${PROJECT_NAME}_${TAG}_${GOOS}_${GOARCH}"
          BINARY_NAME="${PROJECT_NAME}"
          if [ "${GOOS}" = "windows" ]; then
            BINARY_NAME+=".exe"
          fi
          mkdir -p "${PACKAGE_DIR}"
          go build -ldflags="-s -w" -o "${PACKAGE_DIR}/${BINARY_NAME}" ./cmd
          cp config.yml participants.csv README.md "${PACKAGE_DIR}/"
          if [ "${GOOS}" = "windows" ]; then
            ARCHIVE_NAME="${PACKAGE_DIR}.zip"
            7z a "${ARCHIVE_NAME}" "${PACKAGE_DIR}"
          else
            ARCHIVE_NAME="${PACKAGE_DIR}.tar.gz"
            tar -czvf "${ARCHIVE_NAME}" "${PACKAGE_DIR}"
          fi
          echo "asset_path=${ARCHIVE_NAME}" >> $GITHUB_OUTPUT

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-asset-${{ matrix.os }}-${{ matrix.arch }}
          path: ${{ steps.build-and-package.outputs.asset_path }}
          retention-days: 1

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    if: github.event_name == 'push'
    steps:
      - name: Download all release assets
        uses: actions/download-artifact@v4
        with:
          path: release-assets/

      - name: List downloaded files for debugging
        run: ls -R release-assets

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          files: release-assets/*/*
